CREATE TABLE DONOR2
    (DID INT ,
     NAMES VARCHAR(30) ,
     SEX VARCHAR(30),
	 AGE INT,
     Addresss VARCHAR(30),
	 PHNO INT , 
	 PRIMARY KEY(DID));

CREATE TABLE BLOOD3(BLOODTYPE  VARCHAR(30),
	COST INT ,
     CODE INT UNIQUE NOT NULL,
	 b_DID INT,
	 PRIMARY KEY(BLOODTYPE, CODE),
	 FOREIGN KEY(b_DID) REFERENCES DONOR2(DID));

	
	CREATE TABLE BLOODBANK3
    (BNO INT UNIQUE NOT NULL,
     BB_BLOODTYPE VARCHAR(30),
     ORDERS VARCHAR(30),
	 ISSUES VARCHAR(30),
	 B_CODE INT,
	 PRIMARY KEY (BNO,BB_BLOODTYPE),
	 foreign key (B_CODE) references BLOOD3 (CODE)ON DELETE CASCADE);




CREATE TABLE RECEPTIONIST3
    (EMP_ID INT ,
     NAME VARCHAR(30) ,
     Addresss VARCHAR(30),
	 PHNO INT , 
	 BNO INT,
	 DID INT,
	 PRIMARY KEY(EMP_ID),
	 FOREIGN KEY (DID) REFERENCES DONOR2(DID));

	CREATE TABLE HOSPITAL3
    (NAMES VARCHAR(30) ,
     ADDRESS VARCHAR(30),
	 PHNO INT , 
	 BLOODTYPE  VARCHAR(30),
	 h_BNO INT UNIQUE NOT NULL,
	 PRIMARY KEY (NAMES,PHNO),
	 foreign key(h_BNO) REFERENCES BLOODBANK3(BNO) ON DELETE CASCADE);
 


CREATE TABLE BLOODBANK_MANAGER3
    (EMP_ID INT ,
     NAMES VARCHAR(30),
     EMAIL_ID VARCHAR(30),
	 PHNO INT , 
	 M_BNO INT UNIQUE NOT NULL,
	 PRIMARY KEY (NAMES,M_BNO),
	foreign key(M_bno) references bloodbank3(bno)on delete cascade);
